* man/check-man: Force MANWIDTH to 80. Ignore "table wider than line   width" warnings from groff >= 1.20 for now.

diff --git a/man/check-man b/man/check-man
--- a/man/check-man
+++ b/man/check-man
@@ -19,13 +19,21 @@ fi
 [ -x "$top_builddir/src/man" ] || exit 77
 
 code=0
-errors="$(LC_ALL=C "$top_builddir/src/man" --warnings -E UTF-8 -l "$1" 2>&1 >/dev/null)" || code=$?
+errors="$(LC_ALL=C MANWIDTH=80 "$top_builddir/src/man" --warnings -E UTF-8 -l "$1" 2>&1 >/dev/null)" || code=$?
 
 # Ignore wrapping failures for CJK manual pages; this should go away once
 # groff supports these natively.
 case $LINGUA in
 	ja|ko|zh)
 		errors="$(echo "$errors" | $EGREP -v "(cannot adjust line|can't break line)")" || true
+		;;
+esac
+
+# Ignore tbl warnings from groff >= 1.20 for now. These parts of our manual
+# pages should probably be rewritten without tbl.
+case $LINGUA in
+	de|id|it|pl|ru)
+		errors="$(echo "$errors" | $EGREP -v 'table wider than line width')" || true
 		;;
 esac
 
