* m4/man-gcc-warning.m4: New file. * configure.ac: Test whether each -W option (other than -Wall) that   we want to add is supported, rather than adding it   unconditionally. Reported by Peter Breitenlohner.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5577,7 +5577,391 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 CFLAGS="$CFLAGS -Wall"
 if test "$GCC" = yes
 then
-	CFLAGS="$CFLAGS -W -Wpointer-arith -Wwrite-strings -Wstrict-prototypes -Wshadow -Wformat-security -Wno-missing-field-initializers"
+	man_saved_CFLAGS="$CFLAGS"
+ CFLAGS="$CFLAGS -W"
+ { echo "$as_me:$LINENO: checking that GCC supports -W" >&5
+echo $ECHO_N "checking that GCC supports -W... $ECHO_C" >&6; }
+if test "${man_cv_gcc_warning_+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  man_cv_gcc_warning_=no
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  man_cv_gcc_warning_=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $man_cv_gcc_warning_" >&5
+echo "${ECHO_T}$man_cv_gcc_warning_" >&6; }
+ if test "$man_cv_gcc_warning_" = no; then
+   CFLAGS="$man_saved_CFLAGS"
+ fi # -W
+	man_saved_CFLAGS="$CFLAGS"
+ CFLAGS="$CFLAGS -Wpointer-arith"
+ { echo "$as_me:$LINENO: checking that GCC supports -Wpointer-arith" >&5
+echo $ECHO_N "checking that GCC supports -Wpointer-arith... $ECHO_C" >&6; }
+if test "${man_cv_gcc_warning_pointer_arith+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  man_cv_gcc_warning_pointer_arith=no
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  man_cv_gcc_warning_pointer_arith=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $man_cv_gcc_warning_pointer_arith" >&5
+echo "${ECHO_T}$man_cv_gcc_warning_pointer_arith" >&6; }
+ if test "$man_cv_gcc_warning_pointer_arith" = no; then
+   CFLAGS="$man_saved_CFLAGS"
+ fi
+	man_saved_CFLAGS="$CFLAGS"
+ CFLAGS="$CFLAGS -Wwrite-strings"
+ { echo "$as_me:$LINENO: checking that GCC supports -Wwrite-strings" >&5
+echo $ECHO_N "checking that GCC supports -Wwrite-strings... $ECHO_C" >&6; }
+if test "${man_cv_gcc_warning_write_strings+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  man_cv_gcc_warning_write_strings=no
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  man_cv_gcc_warning_write_strings=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $man_cv_gcc_warning_write_strings" >&5
+echo "${ECHO_T}$man_cv_gcc_warning_write_strings" >&6; }
+ if test "$man_cv_gcc_warning_write_strings" = no; then
+   CFLAGS="$man_saved_CFLAGS"
+ fi
+	man_saved_CFLAGS="$CFLAGS"
+ CFLAGS="$CFLAGS -Wstrict-prototypes"
+ { echo "$as_me:$LINENO: checking that GCC supports -Wstrict-prototypes" >&5
+echo $ECHO_N "checking that GCC supports -Wstrict-prototypes... $ECHO_C" >&6; }
+if test "${man_cv_gcc_warning_strict_prototypes+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  man_cv_gcc_warning_strict_prototypes=no
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  man_cv_gcc_warning_strict_prototypes=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $man_cv_gcc_warning_strict_prototypes" >&5
+echo "${ECHO_T}$man_cv_gcc_warning_strict_prototypes" >&6; }
+ if test "$man_cv_gcc_warning_strict_prototypes" = no; then
+   CFLAGS="$man_saved_CFLAGS"
+ fi
+	man_saved_CFLAGS="$CFLAGS"
+ CFLAGS="$CFLAGS -Wshadow"
+ { echo "$as_me:$LINENO: checking that GCC supports -Wshadow" >&5
+echo $ECHO_N "checking that GCC supports -Wshadow... $ECHO_C" >&6; }
+if test "${man_cv_gcc_warning_shadow+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  man_cv_gcc_warning_shadow=no
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  man_cv_gcc_warning_shadow=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $man_cv_gcc_warning_shadow" >&5
+echo "${ECHO_T}$man_cv_gcc_warning_shadow" >&6; }
+ if test "$man_cv_gcc_warning_shadow" = no; then
+   CFLAGS="$man_saved_CFLAGS"
+ fi
+	man_saved_CFLAGS="$CFLAGS"
+ CFLAGS="$CFLAGS -Wformat-security"
+ { echo "$as_me:$LINENO: checking that GCC supports -Wformat-security" >&5
+echo $ECHO_N "checking that GCC supports -Wformat-security... $ECHO_C" >&6; }
+if test "${man_cv_gcc_warning_format_security+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  man_cv_gcc_warning_format_security=no
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  man_cv_gcc_warning_format_security=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $man_cv_gcc_warning_format_security" >&5
+echo "${ECHO_T}$man_cv_gcc_warning_format_security" >&6; }
+ if test "$man_cv_gcc_warning_format_security" = no; then
+   CFLAGS="$man_saved_CFLAGS"
+ fi
+	man_saved_CFLAGS="$CFLAGS"
+ CFLAGS="$CFLAGS -Wno-missing-field-initializers"
+ { echo "$as_me:$LINENO: checking that GCC supports -Wno-missing-field-initializers" >&5
+echo $ECHO_N "checking that GCC supports -Wno-missing-field-initializers... $ECHO_C" >&6; }
+if test "${man_cv_gcc_warning_no_missing_field_initializers+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  man_cv_gcc_warning_no_missing_field_initializers=no
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  man_cv_gcc_warning_no_missing_field_initializers=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $man_cv_gcc_warning_no_missing_field_initializers" >&5
+echo "${ECHO_T}$man_cv_gcc_warning_no_missing_field_initializers" >&6; }
+ if test "$man_cv_gcc_warning_no_missing_field_initializers" = no; then
+   CFLAGS="$man_saved_CFLAGS"
+ fi
 fi
 # Find a good install program.  We prefer a C program (faster),
 # so one script is as good as another.  But avoid the broken or
