* configure.ac: Check for po4a. Define an Automake conditional based   on whether it is present. * man/Makefile.am (SUBDIRS): Add the po4a subdirectory only if the   po4a program is present. * man/po4a/Makefile.am (update-po): Use PO4A variable.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1014,6 +1014,9 @@ POSUB
 LINGUAS
 NLS_TRUE
 NLS_FALSE
+PO4A
+PO4A_TRUE
+PO4A_FALSE
 DBLIBS
 LIBOBJS
 TRANS_APROPOS
@@ -34514,6 +34517,57 @@ else
   NLS_FALSE=
 fi
 
+for ac_prog in po4a
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_PO4A+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$PO4A"; then
+  ac_cv_prog_PO4A="$PO4A" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_PO4A="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+PO4A=$ac_cv_prog_PO4A
+if test -n "$PO4A"; then
+  { echo "$as_me:$LINENO: result: $PO4A" >&5
+echo "${ECHO_T}$PO4A" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$PO4A" && break
+done
+
+
+ if test -n "$PO4A"; then
+  PO4A_TRUE=
+  PO4A_FALSE='#'
+else
+  PO4A_TRUE='#'
+  PO4A_FALSE=
+fi
+
 
 # Checks for structures and compiler characteristics.
 { echo "$as_me:$LINENO: checking for an ANSI C-conforming const" >&5
@@ -37374,6 +37428,13 @@ echo "$as_me: error: conditional \"NLS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${PO4A_TRUE}" && test -z "${PO4A_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"PO4A\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"PO4A\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
@@ -38495,6 +38556,9 @@ POSUB!$POSUB$ac_delim
 LINGUAS!$LINGUAS$ac_delim
 NLS_TRUE!$NLS_TRUE$ac_delim
 NLS_FALSE!$NLS_FALSE$ac_delim
+PO4A!$PO4A$ac_delim
+PO4A_TRUE!$PO4A_TRUE$ac_delim
+PO4A_FALSE!$PO4A_FALSE$ac_delim
 DBLIBS!$DBLIBS$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 TRANS_APROPOS!$TRANS_APROPOS$ac_delim
@@ -38522,7 +38586,7 @@ gltests_LIBOBJS!$gltests_LIBOBJS$ac_delim
 gltests_LTLIBOBJS!$gltests_LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 33; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
