* gnulib: Upgrade to 20080601.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -16151,6 +16151,8 @@ fi
 
 
 
+
+
   gl_source_base='gnulib/lib'
 
 
@@ -16632,7 +16634,9 @@ _ACEOF
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS getopt.$ac_objext"
+
 
 
 
@@ -17037,6 +17041,7 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
 
 
 
+
 for ac_func in atexit
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -17149,6 +17154,7 @@ done
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS canonicalize.$ac_objext"
 
 
@@ -17200,6 +17206,7 @@ _ACEOF
 
 
   if test $ac_cv_func_canonicalize_file_name = no; then
+
 
 
 
@@ -17283,6 +17290,7 @@ echo "${ECHO_T}$gl_cv_have_arbitrary_file_name_length_limit" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS chdir-long.$ac_objext"
 
 
@@ -17309,6 +17317,7 @@ _ACEOF
     : # no wrapper needed
   else
     REPLACE_CHOWN=1
+
 
 
 
@@ -17403,6 +17412,7 @@ echo "${ECHO_T}$ac_cv_func_fchown" >&6; }
 if test $ac_cv_func_fchown = yes; then
   :
 else
+
 
 
 
@@ -17775,6 +17785,7 @@ echo "${ECHO_T}$gl_cv_func_dirfd_macro" >&6; }
 
 
 
+
 for ac_func in dirfd
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -17956,6 +17967,7 @@ _ACEOF
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS basename.$ac_objext"
 
 
@@ -17965,7 +17977,9 @@ _ACEOF
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS dirname.$ac_objext"
+
 
 
 
@@ -18033,6 +18047,7 @@ _ACEOF
 
   if test $ac_cv_func_dup2 = no; then
     HAVE_DUP2=0
+
 
 
 
@@ -18133,6 +18148,8 @@ _ACEOF
 
 
 
+
+
 { echo "$as_me:$LINENO: checking for error_at_line" >&5
 echo $ECHO_N "checking for error_at_line... $ECHO_C" >&6; }
 if test "${ac_cv_lib_error_at_line+set}" = set; then
@@ -18192,6 +18209,7 @@ if test $ac_cv_lib_error_at_line = no; then
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS error.$ac_objext"
 
 fi
@@ -18217,6 +18235,7 @@ fi
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS exitfail.$ac_objext"
 
 
@@ -18233,6 +18252,7 @@ fi
 
   if test $ac_cv_func_fchdir = no; then
     REPLACE_FCHDIR=1
+
 
 
 
@@ -18491,7 +18511,9 @@ echo "${ECHO_T}$gl_cv_next_fcntl_h" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS open-safer.$ac_objext"
+
 
 
 
@@ -18508,6 +18530,7 @@ echo "${ECHO_T}$gl_cv_next_fcntl_h" >&6; }
 cat >>confdefs.h <<\_ACEOF
 #define GNULIB_FCNTL_SAFER 1
 _ACEOF
+
 
 
 
@@ -18797,6 +18820,7 @@ fi
 
 
   :
+
 
 
 
@@ -19307,6 +19331,7 @@ fi
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS getcwd.$ac_objext"
 
 
@@ -19330,6 +19355,7 @@ fi
 
 
   if test $ac_cv_func_getlogin_r = no; then
+
 
 
 
@@ -19377,7 +19403,9 @@ fi
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS getopt.$ac_objext"
+
 
 
 
@@ -19558,6 +19586,7 @@ echo "${ECHO_T}$gl_cv_func_gettimeofday_clobber" >&6; }
  if test $gl_cv_func_gettimeofday_clobber = yes; then
    REPLACE_GETTIMEOFDAY=1
    SYS_TIME_H=sys/time.h
+
 
 
 
@@ -19832,6 +19861,7 @@ _ACEOF
     REPLACE_GETTIMEOFDAY=1
     SYS_TIME_H=sys/time.h
     if test $gl_cv_func_gettimeofday_clobber != yes; then
+
 
 
 
@@ -20399,11 +20429,13 @@ echo "${ECHO_T}$gl_cv_glob_lists_symlinks" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS glob.$ac_objext"
 
 
 
   fi
+
 
 
 
@@ -20483,6 +20515,7 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
   fi
+
 
 
 
@@ -20793,6 +20826,7 @@ if test $ac_cv_func_lstat_dereferences_slashed_symlink = no; then
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS lstat.$ac_objext"
 
 fi
@@ -21026,6 +21060,7 @@ _ACEOF
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS malloc.$ac_objext"
 
 
@@ -21059,6 +21094,7 @@ _ACEOF
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS malloc.$ac_objext"
 
     HAVE_MALLOC_POSIX=0
@@ -21074,6 +21110,64 @@ _ACEOF
 
 
 
+  if test $cross_compiling != no; then
+    # AC_FUNC_MEMCMP as of 2.62 defaults to 'no' when cross compiling.
+    # We default to yes if memcmp appears to exist, which works
+    # better for MinGW.
+    { echo "$as_me:$LINENO: checking whether cross-compiling target has memcmp" >&5
+echo $ECHO_N "checking whether cross-compiling target has memcmp... $ECHO_C" >&6; }
+if test "${ac_cv_func_memcmp_working+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+
+			/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <string.h>
+
+int
+main ()
+{
+int ret = memcmp ("foo", "bar", 0);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_func_memcmp_working=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_func_memcmp_working=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_func_memcmp_working" >&5
+echo "${ECHO_T}$ac_cv_func_memcmp_working" >&6; }
+  fi
   { echo "$as_me:$LINENO: checking for working memcmp" >&5
 echo $ECHO_N "checking for working memcmp... $ECHO_C" >&6; }
 if test "${ac_cv_func_memcmp_working+set}" = set; then
@@ -21164,6 +21258,7 @@ test $ac_cv_func_memcmp_working = no &&
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS memcmp.$ac_objext"
 
 
@@ -21175,6 +21270,7 @@ _ACEOF
 
     :
   fi
+
 
 
 
@@ -21322,6 +21418,7 @@ done
 
 
 
+
 for ac_func in memrchr
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -21437,6 +21534,7 @@ done
 
 
 
+
 for ac_func in memset
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -21540,6 +21638,7 @@ done
   :
 
   fi
+
 
 
 
@@ -21752,6 +21851,7 @@ echo "${ECHO_T}$gl_cv_func_working_mkstemp" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS mkstemp.$ac_objext"
 
 
@@ -21761,6 +21861,7 @@ echo "${ECHO_T}$gl_cv_func_working_mkstemp" >&6; }
 
 
   GNULIB_MKSTEMP=1
+
 
 
 
@@ -21782,6 +21883,9 @@ echo "${ECHO_T}$gl_cv_func_working_mkstemp" >&6; }
 
 
   :
+
+
+
 
 
 
@@ -21911,6 +22015,7 @@ done
   case $ac_cv_func_openat+$ac_cv_func_lstat_dereferences_slashed_symlink in
   yes+yes) ;;
   yes+*)
+
 
 
 
@@ -22113,6 +22218,7 @@ fi
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS fchownat.$ac_objext"
 
 
@@ -22126,6 +22232,7 @@ _ACEOF
 
 
   :
+
 
 
 
@@ -22262,6 +22369,7 @@ done
 
   if test $ac_cv_func_readlink = no; then
     HAVE_READLINK=0
+
 
 
 
@@ -22576,6 +22684,7 @@ _ACEOF
 cat >>confdefs.h <<\_ACEOF
 #define regfree rpl_regfree
 _ACEOF
+
 
 
 
@@ -22904,6 +23013,7 @@ echo "${ECHO_T}$gl_cv_func_rename_trailing_slash_bug" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS rename.$ac_objext"
 
 
@@ -22927,12 +23037,14 @@ _ACEOF
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS same.$ac_objext"
 
 
 
 
   :
+
 
 
 
@@ -22968,6 +23080,7 @@ _ACEOF
 
   if test $ac_cv_func_setenv = no; then
     HAVE_SETENV=0
+
 
 
 
@@ -24120,6 +24233,7 @@ _ACEOF
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS sleep.$ac_objext"
 
     :
@@ -24298,6 +24412,7 @@ echo "${ECHO_T}$gl_cv_func_snprintf_size1" >&6; }
     esac
   fi
   if test $gl_cv_func_snprintf_usable = no; then
+
 
 
 
@@ -25787,6 +25902,7 @@ echo "${ECHO_T}$gl_cv_next_stdlib_h" >&6; }
 
 
 
+
 for ac_func in strcasecmp
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -25891,6 +26007,7 @@ done
   :
 
   fi
+
 
 
 
@@ -26090,6 +26207,7 @@ fi
 
 
 
+
 for ac_func in strchrnul
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -26206,6 +26324,7 @@ done
 
 
 
+
 for ac_func in strcspn
 do
 as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
@@ -26307,6 +26426,7 @@ done
   if test $ac_cv_func_strcspn = no; then
     :
   fi
+
 
 
 
@@ -26435,6 +26555,7 @@ done
 
 
   if test $gl_cv_func_working_strerror = no; then
+
 
 
 
@@ -26666,6 +26787,7 @@ _ACEOF
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS strndup.$ac_objext"
 
     :
@@ -26771,6 +26893,7 @@ test $ac_cv_func_strnlen_working = no &&
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS strnlen.$ac_objext"
 
 
@@ -26790,6 +26913,7 @@ _ACEOF
 
 
   GNULIB_STRNLEN=1
+
 
 
 
@@ -26907,6 +27031,7 @@ done
 
 
   GNULIB_STRPBRK=1
+
 
 
 
@@ -27212,6 +27337,7 @@ echo "${ECHO_T}$gl_cv_func_working_strsignal" >&6; }
     if test $ac_cv_func_strsignal = yes; then
       REPLACE_STRSIGNAL=1
     fi
+
 
 
 
@@ -28289,6 +28415,7 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS tempname.$ac_objext"
 
 
@@ -28380,6 +28507,7 @@ echo "${ECHO_T}$gl_cv_next_unistd_h" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS dup-safer.$ac_objext"
 
 
@@ -28389,7 +28517,9 @@ echo "${ECHO_T}$gl_cv_next_unistd_h" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS fd-safer.$ac_objext"
+
 
 
 
@@ -28506,6 +28636,7 @@ done
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS unsetenv.$ac_objext"
 
 
@@ -28611,7 +28742,9 @@ echo "${ECHO_T}$gt_cv_func_unsetenv_ret" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS vasnprintf.$ac_objext"
+
 
 
 
@@ -28629,7 +28762,9 @@ echo "${ECHO_T}$gt_cv_func_unsetenv_ret" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS printf-parse.$ac_objext"
+
 
 
 
@@ -29002,7 +29137,9 @@ done
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS vasprintf.$ac_objext"
+
 
 
 
@@ -29219,6 +29356,7 @@ echo "${ECHO_T}$gl_cv_func_snprintf_size1" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS vsnprintf.$ac_objext"
 
   if test $ac_cv_func_vsnprintf = yes; then
@@ -29391,11 +29529,51 @@ if test "${gl_cv_func_iswcntrl_works+set}" = set; then
 else
 
           if test "$cross_compiling" = yes; then
-  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling
-See \`config.log' for more details." >&5
-echo "$as_me: error: cannot run test program while cross compiling
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <stdlib.h>
+                          #if __GNU_LIBRARY__ == 1
+                          Linux libc5 i18n is broken.
+                          #endif
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  gl_cv_func_iswcntrl_works=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	gl_cv_func_iswcntrl_works=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
 else
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -29522,6 +29700,7 @@ echo "${ECHO_T}$gl_cv_next_wctype_h" >&6; }
 
 
 
+
   gl_LIBOBJS="$gl_LIBOBJS xmalloc.$ac_objext"
 
 
@@ -29531,6 +29710,7 @@ echo "${ECHO_T}$gl_cv_next_wctype_h" >&6; }
 
 
   :
+
 
 
 
@@ -29711,6 +29891,11 @@ done
 
 
 
+
+
+
+
+
   gltests_libdeps=
   gltests_ltlibdeps=
 
@@ -29719,7 +29904,12 @@ done
 
 
 
+
+
   gl_source_base='tests'
+
+
+
 
 
 
